### ISSUE TITLE
Version .jar

### ISSUE THREAD

**Issue by ledevmacedo** [dmulloy2/ChestShop-3#15]
Would it be possible to make a .java version available? I do not understand Plugin Compilation, it would help me a lot

Thank you.

Sorry for my English.

**Comment by dmulloy2** [comment]
The source code is available here. Just click the code tab and navigate the file structure.

**Comment by NicoNekoDev** [comment]
"If you can release a jar on github..." because he don't know how to compile.
BTW @BrazilianBug you can download the jar here: [http://ci.dmulloy2.net/job/ChestShop](url)

**Comment by dmulloy2** [comment]
@nicuch Ah gotcha. I thought he meant the .java source files lol

Yeah you can find the compiled plugin at http://ci.dmulloy2.net/job/ChestShop
