### ISSUE TITLE
Jar download link

### ISSUE THREAD

**Issue by galaipa** [dmulloy2/ChestShop-3#4]
Hi!
I have seen you have updated chestshop :+1: Nice work! Is this project public? I mean, could you send me the jar. I need it for a 1.9 server.

Thanks

**Comment by dmulloy2** [comment]
I can throw it up on my Jenkins when I get the chance, but you can always clone the git repo and use `mvn clean install`

**Comment by galaipa** [comment]
I tried, but there are too many dependences xD

**Comment by dmulloy2** [comment]
Live here: http://ci.dmulloy2.net/job/ChestShop/

**Comment by galaipa** [comment]
Thank you very much :+1:
