### ISSUE TITLE
UUID - Username CS database is broken

### ISSUE THREAD

**Issue by L4BORG** [dmulloy2/ChestShop-3#8]
Ref: 
- https://github.com/dmulloy2/ChestShop-3/commit/8c7594be51bc6053a30a111e8ac3c15acd280bce
- https://github.com/drtshock/Essentials/issues/855

The issue starts here https://github.com/dmulloy2/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Listeners/Player/PlayerConnect.java after that username should be stored or updated based on UUID and not the other way around otherwise we're bugging Economies and causing bunch other issues. I'm not sure how's CS handling that tho...

But as I've already pointed out, there's another issue - signs contain usernames and not UUIDs, because of the way how CS works sign locations are not stored (meaning signs can not be updated with new usernames without loading whole world(s)). So the downside would be player losing his chest shops (which is not as bad as kicking players or bugging economy plugins, etc...).

**Comment by dmulloy2** [comment]
I reread this and I gotta say I'm a little lost. What exactly is the issue that this causes?

**Comment by L4BORG** [comment]
IMO CS is not updating UUID<->Username database when a user changes his username. Handling this the usual way (removing old data from DB in adding new data, or updating username for UUID) could break builtin chestshop protection (used ID used for builtin protection is actually on the sign).

So you have user Tester with some UUID and CS signs that contain username "Tester", just updating username for UUID (in CS database) would break that (since username Tester won't have pair in Username<->UUID database anymore).

**Comment by L4BORG** [comment]
It wouldn't be an issue for us since we don't use builtin protection but it is enabled by default IIRC.

Also, CS is handling usernames 16 characters long with that database (you can only fit 15 characters in 1 line on the sign).
